config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only:[:create, :index, :show, :edit, :destroy, :update]
  resources :users, only:[:create, :index, :show, :edit, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sing_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]= "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def show
    @bookes = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to book_path(@book.id)
    else
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def abuot
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    @user.save
    redirect_to user_path(@user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render action: :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  	  	<h1>Editing Book</h1>
  		  <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  		    <div class="d-flex flex-column bd-highlight mb-3">
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class:"form-control", placeholder:"" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class:"form-control", rows:"3", placeholder:"" %>
            </div>
            <div class="form-group">
              <%= f.submit 'Update Book', class:"btn btn-success" %>
            </div>
          </div>
        <% end %>
  		  <%= link_to "Show", book_path(@book) %> |
  		  <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
  <main>
    <p id="notice"><%= flash[:notice] %></p>
    <div class="container px-5 px-sm-0">
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <%= @book.errors.count %> errors prohibited this obj from being saved:
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-3">
          <%= render 'users/list', user: @user %>
          <h2 class="mt-3">New book</h2>
          <%= form_with model:@book, url:"/books", local:true do |f| %>
            <div class="d-flex flex-column bd-highlight mb-3">
              <div class="form-group">
                <label for="book_title">Title</label>
                <%= f.text_field :title, class:"form-control", placeholder:"" %>
              </div>
              <div class="form-group">
                <label for="book_opinion">Opinion</label>
                <%= f.text_area :body, class:"form-control", placeholder:"" %>
              </div>
              <div class="form-group">
                <%= f.submit 'Create Book', class:"btn btn-success" %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user.id) do %>
                      <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body  %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>

app/views/books/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/list', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@bookes, url:"/books", local:true do |f| %>
          <div class="d-flex flex-column bd-highlight mb-3">
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class:"form-control" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book', class:"btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
  		  <h2>Book detail</h2>
  		  <table class="table">
  		    <tbody>
  		      <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %> <br>
                  <%= @user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <% if @user.id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@book), class:'btn btn-sm btn-success edit_book_26052' %></td>
                <td><%= link_to "Destroy", book_path(@book.id), class:'btn btn-sm btn-danger destroy_book_26052',  method: :delete, "data-confirm" => "本当に消しますか?" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class:'btn btn-info btn-sm btn-block mb-3 sign_in' %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class:'btn btn-success btn-sm btn-block sign_up' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <%= link_to "Bookers", root_path, class:'navbar-brand' %>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to " Home", user_path(current_user.id), class:'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " Users", users_path, class:'fas fa-users nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " Books", books_path, class:'fas fa-book-open nav-link text-light' %>
                </li>
                <li>
                  <%= link_to " Log out", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <% else %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <%= link_to "Bookers", root_path, class:'navbar-brand' %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse show" id="navbarNavDropdown" style="">
              <ul class="navbar-nav ml-auto">
                <li><%= link_to "Home", root_path, class:'fas fa-home nav-link text-light' %></li>
                <li><%= link_to "About", home_about_path, class:'fas fa-link nav-link text-light' %></li>
                <li><%= link_to " Sign up", new_user_registration_path, class:'fas fa-user-plus nav-link text-light' %></li>
                <li><%= link_to " Log in", new_user_session_path, class:'fas fa-sign-in-alt nav-link text-light' %></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <% end %>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr>
	     <th>name</th>
	     <th><%= user.name %></th>
    </tr>
    <tr>
	     <th>introduction</th>
	     <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to "", edit_user_path(user), class:'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_31562' %>
</div>

app/views/users/edit.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <% if @user.errors.any? %>
    <%= @user.errors.count %>errors prohibited this obj from being saved:
    <% @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model:@user, url:"/users/#{@user.id}", local:true do |f| %>
          <div class="d-flex flex-column bd-highlight mb-3">
            <div class="form-group">
              <label for="user_name">Name</label>
              <%= f.text_field :name, class:"form-control", placeholder:"" %>
            </div>
            <div class="form-group">
              <label for="user_image">Image</label>
              <%= f.attachment_field :profile_image, class: "w-100" %>
            </div>
            <div class="form-group">
              <label for="user_introduction">Introduction</label>
              <%= f.text_area :introduction, class:"form-control", rows:"3", placeholder:"" %>
            </div>
            <div class="form-group">
              <%= f.submit 'Update User', class:"btn btn-secondary" %>
            </div>
          </div
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice">
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/list', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book, url:"/books", local:true do |f| %>
          <div class="d-flex flex-column bd-highlight mb-3">
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class:"form-control", placeholder:"" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class:"form-control", placeholder:"" %>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book', class:"btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/list', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book, url:"/books", local:true do |f| %>
          <div class="d-flex flex-column bd-highlight mb-3">
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class:"form-control", placeholder:"" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class:"form-control", placeholder:"" %>
            </div>
            <div class="form-group">
              <%= f.submit 'Create Book', class:"btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(@user.id) do %>
                    <%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>